apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: kikis
data:
  nginx.conf: |-
    #CODE1.0:
    #add the nginx.conf configuration - this will be referenced within the deployment.yaml
